country=["nigeria", "south africa", "canada", "france", "india", "kenya"]
print("length of list:",len(country))
print("first element is:", country[0])
print("last element is:", country[-1])
country.append("dubai")
print("updated list:", country)
country.remove("south africa")
print("updated list:", country)
country.sort()
print("updated list:", country)
country.pop(1)
print("updated list:", country)
country.reverse()
print("reversed list:", country)
print("multiplication list:", country*2)
country=country[:5]
print("sliced list:", country)
country.clear()
print("updated list:", country)